/********************************************************************************
 * Soriku IDE — chat model: fold engine SSE events into a view turn (pure)
 *
 * SPDX-License-Identifier: MIT
 ********************************************************************************/

import { AgentPersona, ConversationMessage, SorikuSseEvent } from 'soriku-engine-client-ext/lib/common/engine-types';

export type ToolOutcome = 'ok' | 'blocked' | 'salvaged' | 'denied' | 'error' | 'verify_failed' | 'verified';

export interface ChatToolCall {
    callId?: string;
    /** Owning worker (multi-agent runs) — scopes result/outcome matching (#7). */
    workerId?: string;
    tool: string;
    args?: unknown;
    status: 'requested' | 'running' | 'done';
    result?: unknown;
    /** Reliability outcome from the engine: did it run cleanly, get blocked, or get recovered? */
    outcome?: ToolOutcome;
    /** Human-readable reason for a blocked/salvaged/denied outcome. */
    outcomeReason?: string;
}

export interface PlanTaskView {
    id: string;
    role: string;
    goal: string;
    model?: string;
}

export interface PendingPlan {
    planId: string;
    tasks: PlanTaskView[];
    costEur?: number;
}

export interface GeneratedFileView {
    path: string;
    filename?: string;
}

/** One worker/agent in a plan run — the unit the Fleet view renders. */
export interface AgentActivity {
    workerId: string;
    taskId?: string;
    /** Worker role (backend-developer, code-reviewer, …). */
    role?: string;
    /** Model the worker runs on. */
    model?: string;
    /** Persona/agent id when the conductor assigned one (else a bare role worker). */
    personaId?: string;
    /** Human agent name when the worker runs under a persona (from worker_start). */
    agentName?: string;
    /** Head agent id when this worker is a minion (Fase F) — the Fleet nests it under that head. */
    parentAgentId?: string;
    status: 'running' | 'done' | 'error';
    /** Files this worker wrote (paths). */
    files: string[];
    /** Count of tool calls the engine blocked/recovered for this worker (reliability signal). */
    corrections: number;
    /** Review verdict when this worker is a reviewer (code-reviewer / editor). */
    verdict?: { status: 'approved' | 'changes_requested'; notes?: string };
}

export interface AssistantTurn {
    role: 'assistant';
    id: string;
    /** Model that produced this answer — surfaced for transparency (from SSE meta). */
    model?: string;
    /** Who responded (agent name / role) from SSE meta. */
    respondedBy?: string;
    conversationId?: string;
    text: string;
    toolCalls: ChatToolCall[];
    /** Files written during this turn (from engine history). */
    generatedFiles: GeneratedFileView[];
    /** Models that collaborated on this answer (multi-worker / ensemble), for transparency. */
    workers: string[];
    /** Structured per-worker activity for the Fleet view (multi-agent runs). */
    agents: AgentActivity[];
    /** Plan generated by the engine (Plan mode), shown for approval. */
    pendingPlan?: PendingPlan;
    /** The engine has parked the plan and is waiting for execute/cancel. */
    awaitingApproval?: boolean;
    /** Widget flag: this turn's plan must be approved by the user (Plan mode). */
    planNeedsApproval?: boolean;
    /** Latest progress message from the engine (status / plan / worker events). */
    phase?: string;
    /** Set when the engine escalated to another model (e.g. timed-out local → cloud). */
    escalation?: { from?: string; to?: string; reason?: string };
    /** Time to first token (ms) — from SSE `timing` event. */
    ttftMs?: number;
    /** Total stream duration (ms) — from SSE `done` event. */
    totalMs?: number;
    /**
     * `interrupted` = the transport dropped mid-turn (#5): the partial answer is
     * kept and labeled retryable — distinct from `error` (engine-reported failure).
     */
    status: 'streaming' | 'done' | 'error' | 'interrupted';
    error?: string;
    /** The turn failed on authentication (#14): the UI offers sign-in + retry. */
    authRequired?: boolean;
}

export interface UserMessage {
    role: 'user';
    id: string;
    text: string;
}

export type ChatMessage = UserMessage | AssistantTurn;

export function createAssistantTurn(id: string): AssistantTurn {
    return { role: 'assistant', id, text: '', toolCalls: [], generatedFiles: [], workers: [], agents: [], status: 'streaming' };
}

function cloneGeneratedFiles(files: GeneratedFileView[]): GeneratedFileView[] {
    return files.map(f => ({ ...f }));
}

/** The model behind a worker event — never the opaque worker_id (kept out of the UI list). */
function workerModelOf(event: SorikuSseEvent): string | undefined {
    return asString(event.model) ?? asString(event.model_id);
}

function parsePlanTasks(raw: unknown): PlanTaskView[] {
    if (!Array.isArray(raw)) {
        return [];
    }
    return raw.map((t, i) => {
        const task = (t && typeof t === 'object' ? t : {}) as Record<string, unknown>;
        return {
            id: asString(task.id) ?? `t${i + 1}`,
            role: asString(task.role) ?? 'worker',
            goal: asString(task.goal) ?? '',
            model: asString(task.preferred_model) ?? undefined,
        };
    });
}

function asString(value: unknown): string | undefined {
    return typeof value === 'string' ? value : undefined;
}

function callIdOf(event: SorikuSseEvent): string | undefined {
    return asString(event.request_id) ?? asString(event.confirmation_id) ?? asString(event.call_id) ?? asString(event.id);
}

/**
 * Index of the last tool call that has not completed yet (for matching results without an id).
 * Scoped per worker (#7): pass 1 only matches entries with the SAME owner (both-undefined =
 * the single-agent path); pass 2 lets a worker event ADOPT an unowned entry — a delegated
 * `tool_request` carries no worker_id, so its entry is unowned until the worker claims it (#8) —
 * but an event can never bind to an entry owned by a DIFFERENT worker.
 */
function lastUnfinished(calls: ChatToolCall[], tool?: string, workerId?: string): number {
    for (let i = calls.length - 1; i >= 0; i--) {
        const c = calls[i];
        if (c.status !== 'done' && (tool === undefined || c.tool === tool) && c.workerId === workerId) {
            return i;
        }
    }
    if (workerId !== undefined) {
        for (let i = calls.length - 1; i >= 0; i--) {
            const c = calls[i];
            if (c.status !== 'done' && (tool === undefined || c.tool === tool) && c.workerId === undefined) {
                return i;
            }
        }
    }
    return -1;
}

/** Union of two path lists, order-preserving, de-duplicated. */
function mergeFilePaths(existing: string[] | undefined, add: string[]): string[] {
    const out = (existing ?? []).slice();
    for (const p of add) {
        if (p && !out.includes(p)) {
            out.push(p);
        }
    }
    return out;
}

/** Upsert a worker's Fleet activity by workerId; merges the patch immutably. */
function upsertAgent(agents: AgentActivity[], workerId: string, patch: Partial<AgentActivity>): void {
    const idx = agents.findIndex(a => a.workerId === workerId);
    if (idx >= 0) {
        agents[idx] = { ...agents[idx], ...patch, files: patch.files ?? agents[idx].files };
    } else {
        agents.push({ workerId, status: 'running', files: [], corrections: 0, ...patch });
    }
}

/**
 * Find a tool call by callId, falling back to the most recent entry with a matching tool —
 * scoped to the event's worker (#7): same-owner first, then unowned entries (adoptable),
 * never another worker's.
 */
function findToolCallIndex(calls: ChatToolCall[], callId?: string, tool?: string, workerId?: string): number {
    if (callId) {
        const byId = calls.findIndex(c => c.callId === callId);
        if (byId >= 0) {
            return byId;
        }
    }
    for (let i = calls.length - 1; i >= 0; i--) {
        if ((tool === undefined || calls[i].tool === tool) && calls[i].workerId === workerId) {
            return i;
        }
    }
    if (workerId !== undefined) {
        for (let i = calls.length - 1; i >= 0; i--) {
            if ((tool === undefined || calls[i].tool === tool) && calls[i].workerId === undefined) {
                return i;
            }
        }
    }
    return -1;
}

/**
 * Upsert a tool call: reuse the matching/last-unfinished entry so an engine event and its
 * delegated `tool_request` don't show as duplicates, then resolve it on `tool_result`.
 * Worker events stamp their workerId on the entry they claim (#7/#8).
 */
function upsertToolCall(calls: ChatToolCall[], event: SorikuSseEvent, status: ChatToolCall['status']): void {
    const callId = callIdOf(event);
    const tool = asString(event.tool) ?? 'tool';
    const workerId = asString(event.worker_id);
    let idx = callId ? calls.findIndex(c => c.callId === callId) : -1;
    if (idx < 0) {
        idx = lastUnfinished(calls, tool, workerId);
    }
    if (idx >= 0) {
        calls[idx] = {
            ...calls[idx], status, tool,
            args: event.args ?? calls[idx].args,
            callId: callId ?? calls[idx].callId,
            workerId: workerId ?? calls[idx].workerId,
        };
    } else {
        calls.push({ callId, tool, args: event.args, status, workerId });
    }
}

/**
 * Fold one SSE event into the current assistant turn. Pure & immutable: returns a new turn so the
 * widget can keep prior snapshots and the logic is unit-testable without Theia or the network.
 */
export function reduceSseEvent(turn: AssistantTurn, event: SorikuSseEvent): AssistantTurn {
    const next: AssistantTurn = {
        ...turn,
        toolCalls: turn.toolCalls.slice(),
        workers: turn.workers.slice(),
        agents: turn.agents.map(a => ({ ...a, files: a.files.slice() })),
        generatedFiles: cloneGeneratedFiles(turn.generatedFiles),
    };
    switch (event.type) {
        case 'meta':
            next.model = asString(event.model) ?? next.model;
            next.respondedBy = asString(event.responded_by) ?? asString(event.agent_name) ?? asString(event.role) ?? next.respondedBy;
            next.conversationId = asString(event.conversation_id) ?? next.conversationId;
            break;
        case 'model_switch':
        case 'model_assist':
            next.model = asString(event.to) ?? asString(event.model) ?? next.model;
            break;
        case 'routing':
            next.model = asString(event.model) ?? next.model;
            break;
        case 'status':
            next.phase = asString(event.content) ?? asString(event.message) ?? asString(event.status) ?? next.phase;
            break;
        case 'plan_generated': {
            next.phase = 'Planning…';
            const tasks = parsePlanTasks(event.tasks);
            const planId = asString(event.plan_id);
            if (planId) {
                next.pendingPlan = { planId, tasks, costEur: next.pendingPlan?.costEur };
            }
            break;
        }
        case 'deprecated_mode_translation':
            next.phase = 'Planning workers…';
            break;
        case 'plan_cost_estimated':
            if (next.pendingPlan && typeof event.estimated_cost_eur === 'number') {
                next.pendingPlan = { ...next.pendingPlan, costEur: event.estimated_cost_eur };
            }
            break;
        case 'plan_awaiting_execution':
            next.awaitingApproval = true;
            next.phase = 'Awaiting your approval';
            break;
        case 'worker_start': {
            next.awaitingApproval = false;
            const model = workerModelOf(event);
            if (model && !next.workers.includes(model)) {
                next.workers.push(model);
            }
            const taskId = asString(event.task_id);
            const workerId = asString(event.worker_id);
            if (workerId) {
                upsertAgent(next.agents, workerId, {
                    taskId,
                    role: asString(event.role),
                    model,
                    personaId: asString(event.persona_id),
                    agentName: asString(event.agent_name),
                    parentAgentId: asString(event.parent_agent_id),
                    status: 'running',
                });
            }
            next.phase = model
                ? (taskId ? `Worker ${taskId}: ${model}` : `Worker answering: ${model}`)
                : 'Workers answering…';
            break;
        }
        case 'worker_chunk': {
            const chunk = asString(event.chunk) ?? asString(event.content) ?? '';
            if (chunk) {
                next.text += chunk;
            }
            const model = workerModelOf(event);
            if (model && !next.workers.includes(model)) {
                next.workers.push(model);
            }
            break;
        }
        case 'worker_done': {
            const model = workerModelOf(event);
            if (model && !next.workers.includes(model)) {
                next.workers.push(model);
            }
            const result = (event.result && typeof event.result === 'object' ? event.result : {}) as Record<string, unknown>;
            const gen = (event.generated_files ?? result.generated_files) as unknown;
            const doneFiles = parseGeneratedFiles(gen);
            doneFiles.forEach(f => {
                if (!next.generatedFiles.some(g => g.path === f.path)) {
                    next.generatedFiles.push(f);
                }
            });
            const workerId = asString(event.worker_id);
            if (workerId) {
                const errored = !!(result.error || event.error);
                upsertAgent(next.agents, workerId, {
                    status: errored ? 'error' : 'done',
                    files: mergeFilePaths(next.agents.find(a => a.workerId === workerId)?.files, doneFiles.map(f => f.path)),
                });
            }
            const taskId = asString(event.task_id) ?? asString(result.task_id);
            if (taskId && next.pendingPlan) {
                next.phase = `Worker done: ${taskId}`;
            }
            break;
        }
        case 'generated_files': {
            parseGeneratedFiles(event.files).forEach(f => {
                if (!next.generatedFiles.some(g => g.path === f.path)) {
                    next.generatedFiles.push(f);
                }
            });
            break;
        }
        case 'escalation': {
            next.escalation = {
                from: asString(event.from),
                to: asString(event.to),
                reason: asString(event.reason),
            };
            next.phase = `Escalated to ${asString(event.to) ?? 'another model'}`;
            break;
        }
        case 'review_verdict': {
            const workerId = asString(event.worker_id);
            const status = asString(event.status);
            if (workerId && (status === 'approved' || status === 'changes_requested')) {
                upsertAgent(next.agents, workerId, {
                    verdict: { status, notes: asString(event.notes) },
                });
            }
            break;
        }
        case 'worker_tool_call': {
            const failed = !!event.error;
            upsertToolCall(next.toolCalls, event, 'done');
            const outcome = asString(event.outcome) as ToolOutcome | undefined;
            if (outcome && outcome !== 'ok') {
                const callId = callIdOf(event);
                const tool = asString(event.tool);
                const idx = findToolCallIndex(next.toolCalls, callId, tool, asString(event.worker_id));
                if (idx >= 0) {
                    next.toolCalls[idx] = {
                        ...next.toolCalls[idx],
                        outcome,
                        outcomeReason: asString(event.outcome_reason) ?? next.toolCalls[idx].outcomeReason,
                    };
                }
            }
            const toolPath = asString((event.args && typeof event.args === 'object'
                ? event.args as Record<string, unknown> : {}).path);
            if (!failed && toolPath && (event.tool === 'file_write' || event.tool === 'apply_patch')) {
                if (!next.generatedFiles.some(g => g.path === toolPath)) {
                    next.generatedFiles.push({ path: toolPath, filename: toolPath.split('/').pop() ?? toolPath });
                }
            }
            // Attribute the write + any engine correction to the worker's Fleet row.
            const callWorkerId = asString(event.worker_id);
            if (callWorkerId) {
                const existing = next.agents.find(a => a.workerId === callWorkerId);
                const isWrite = !failed && toolPath && (event.tool === 'file_write' || event.tool === 'apply_patch');
                const corrected = outcome === 'blocked' || outcome === 'salvaged' || outcome === 'verify_failed';
                upsertAgent(next.agents, callWorkerId, {
                    files: isWrite ? mergeFilePaths(existing?.files, [toolPath]) : (existing?.files ?? []),
                    corrections: (existing?.corrections ?? 0) + (corrected ? 1 : 0),
                });
            }
            if (typeof event.tool === 'string') {
                next.phase = failed ? `${event.tool} failed` : `Wrote ${event.tool === 'file_write' ? 'file' : event.tool}…`;
            }
            break;
        }
        case 'synthesis_start':
            next.awaitingApproval = false;
            next.phase = 'Merging answers…';
            break;
        case 'timing': {
            const ttft = event.ttft_ms;
            if (typeof ttft === 'number' && ttft >= 0) {
                next.ttftMs = ttft;
            }
            break;
        }
        case 'synthesis_chunk':
            next.text += asString(event.chunk) ?? asString(event.content) ?? '';
            break;
        case 'synthesis_done': {
            const finalText = asString(event.final_text);
            if (finalText) {
                next.text = finalText;
            }
            next.model = asString(event.synthesizer_model) ?? next.model;
            next.phase = undefined;
            break;
        }
        case 'plan_done': {
            next.awaitingApproval = false;
            const finalText = asString(event.final_response);
            if (finalText) {
                next.text = finalText;
            }
            if (next.status === 'streaming') {
                next.status = 'done';
            }
            break;
        }
        case 'plan_cancelled':
            next.awaitingApproval = false;
            next.phase = undefined;
            if (next.status === 'streaming') {
                next.status = 'done';
            }
            if (!next.text) {
                next.text = 'Plan cancelled.';
            }
            break;
        case 'plan_failed':
        case 'plan_no_conductor':
            next.awaitingApproval = false;
            next.status = 'error';
            next.error = asString(event.error) ?? asString(event.reason) ?? 'Plan failed';
            break;
        case 'chunk':
            next.text += asString(event.content) ?? '';
            break;
        case 'answer': {
            const answer = asString(event.content) ?? asString(event.answer);
            if (answer) {
                next.text = answer;
            }
            break;
        }
        case 'confirm_tool':
            upsertToolCall(next.toolCalls, event, 'requested');
            break;
        case 'tool_request':
        case 'tool_call':
            upsertToolCall(next.toolCalls, event, 'running');
            break;
        case 'tool_result': {
            const callId = callIdOf(event);
            let idx = callId ? next.toolCalls.findIndex(t => t.callId === callId) : -1;
            if (idx < 0) {
                // Scoped per worker (#7): a result may only resolve its own worker's
                // (or an unowned) pending call, never another worker's.
                idx = lastUnfinished(next.toolCalls, asString(event.tool), asString(event.worker_id));
            }
            if (idx >= 0) {
                next.toolCalls[idx] = { ...next.toolCalls[idx], status: 'done', result: event.result ?? event.output };
            }
            break;
        }
        case 'error':
            next.status = 'error';
            next.error = asString(event.content) ?? asString(event.message) ?? 'Stream error';
            break;
        case 'transport_error':
            // A malformed SSE frame is transport noise, not an engine answer (#3):
            // skip the frame and keep streaming — flipping the whole turn to a
            // permanent error here is exactly the bug this case fixes.
            break;
        case 'done': {
            const total = event.total_ms;
            if (typeof total === 'number' && total >= 0) {
                next.totalMs = total;
            }
            const ttft = event.ttft_ms;
            if (typeof ttft === 'number' && ttft >= 0) {
                next.ttftMs = ttft;
            }
            if (next.status === 'streaming') {
                next.status = 'done';
            }
            break;
        }
        default:
            break;
    }
    return next;
}

/**
 * Map a stored engine conversation (user/assistant messages) into chat view
 * messages, so a saved conversation can be reopened with its history. Empty
 * assistant placeholders and non user/assistant roles are skipped; tool/plan
 * detail isn't re-streamed (history shows the final text).
 */
function parseGeneratedFiles(raw: unknown): GeneratedFileView[] {
    if (!Array.isArray(raw)) {
        return [];
    }
    return raw.map(entry => {
        const item = (entry && typeof entry === 'object' ? entry : {}) as Record<string, unknown>;
        const path = asString(item.path) ?? asString(item.filename) ?? '';
        return { path, filename: asString(item.filename) ?? undefined };
    }).filter(f => f.path.length > 0);
}

function parseHistoryToolCalls(raw: unknown): ChatToolCall[] {
    if (!Array.isArray(raw)) {
        return [];
    }
    return raw.map(step => {
        const item = (step && typeof step === 'object' ? step : {}) as Record<string, unknown>;
        return {
            tool: asString(item.tool) ?? 'tool',
            args: item.args,
            status: 'done' as const,
            result: item.result,
        };
    });
}

function parseHistoryWorkers(raw: unknown): string[] {
    if (!Array.isArray(raw)) {
        return [];
    }
    const models: string[] = [];
    raw.forEach(entry => {
        const item = (entry && typeof entry === 'object' ? entry : {}) as Record<string, unknown>;
        const model = asString(item.model);
        if (model && !models.includes(model)) {
            models.push(model);
        }
    });
    return models;
}

export function fromEngineMessages(messages: ConversationMessage[]): ChatMessage[] {
    const out: ChatMessage[] = [];
    messages.forEach((m, i) => {
        const text = typeof m.content === 'string' ? m.content : '';
        if (m.role === 'user') {
            out.push({ role: 'user', id: `h${i}`, text });
        } else if (m.role === 'assistant' && (text || Array.isArray(m.steps) || Array.isArray(m.workers))) {
            out.push({
                role: 'assistant',
                id: `h${i}`,
                text,
                model: m.model ?? undefined,
                respondedBy: asString(m.agent_name) ?? undefined,
                toolCalls: parseHistoryToolCalls(m.steps),
                generatedFiles: parseGeneratedFiles(m.generated_files),
                workers: parseHistoryWorkers(m.workers),
                agents: [],
                status: 'done',
            });
        }
    });
    return out;
}

/** Compact label for a tool call card in the chat panel. */
export function formatToolCallSummary(call: ChatToolCall): {
    title: string;
    subtitle?: string;
    preview?: string;
    isWrite: boolean;
} {
    const args = call.args && typeof call.args === 'object'
        ? call.args as Record<string, unknown>
        : {};
    const path = typeof args.path === 'string' ? args.path : undefined;
    const base = path?.split('/').pop();
    if (call.tool === 'file_write' && path) {
        const content = typeof args.content === 'string' ? args.content : '';
        const lines = content ? content.split('\n').length : 0;
        const preview = content
            ? content.split('\n').slice(0, 10).join('\n') + (lines > 10 ? '\n…' : '')
            : undefined;
        return {
            title: `Created ${base}`,
            subtitle: path,
            preview,
            isWrite: true,
        };
    }
    if (call.tool === 'apply_patch' && path) {
        return { title: `Patched ${base}`, subtitle: path, isWrite: true };
    }
    if (call.tool === 'file_read' && path) {
        return { title: `Read ${base ?? path}`, subtitle: path, isWrite: false };
    }
    if (call.tool === 'list_directory') {
        const dir = path ?? '.';
        return { title: 'Listed directory', subtitle: dir, isWrite: false };
    }
    return { title: call.tool, isWrite: false };
}

/** Human-readable label for the busy indicator while a turn is still streaming. */
export function busyPhase(turn: AssistantTurn): string {
    const running = turn.toolCalls.find(c => c.status !== 'done');
    if (running) {
        return running.status === 'requested' ? `Awaiting approval: ${running.tool}` : `Running ${running.tool}…`;
    }
    if (turn.phase) {
        return turn.phase;
    }
    return turn.text ? 'Writing…' : 'Thinking…';
}

/** Distilled, render-ready view of what an agent has learned (Fase E insights). */
export interface AgentInsights {
    topPatterns: { keyword: string; weight: number }[];
    domainRules: string[];
    antiPatterns: string[];
    specializations: string[];
    interactions?: number;
}

/** Coerce a domain-rule entry (string, or {rule, ...}) to a display string. */
function ruleText(entry: unknown): string | undefined {
    if (typeof entry === 'string') {
        return entry;
    }
    if (entry && typeof entry === 'object') {
        const r = (entry as Record<string, unknown>).rule;
        if (typeof r === 'string') {
            return r;
        }
    }
    return undefined;
}

/**
 * Summarise an agent persona into the insights the IDE panel shows: the top
 * learned decision keywords, promoted domain rules / anti-patterns,
 * specializations, and interaction count. Pure + defensive — the engine's
 * memory shape varies (decision_patterns may be a flat map or {patterns: {…}}).
 */
export function summarizeAgentInsights(persona: AgentPersona): AgentInsights {
    const memory = (persona.memory ?? {}) as Record<string, unknown>;
    const dpRaw = (memory.decision_patterns ?? {}) as Record<string, unknown>;
    const patternMap = (dpRaw.patterns && typeof dpRaw.patterns === 'object'
        ? dpRaw.patterns
        : dpRaw) as Record<string, unknown>;
    const topPatterns = Object.entries(patternMap)
        .filter(([, w]) => typeof w === 'number')
        .map(([keyword, w]) => ({ keyword, weight: w as number }))
        .sort((a, b) => b.weight - a.weight)
        .slice(0, 8);

    const intelligence = (persona.intelligence ?? {}) as { domain_rules?: unknown[]; anti_patterns?: unknown[] };
    const domainRules = (intelligence.domain_rules ?? []).map(ruleText).filter((r): r is string => !!r);
    const antiPatterns = (intelligence.anti_patterns ?? []).map(ruleText).filter((r): r is string => !!r);
    const specializations = (persona.specializations ?? []).map(s => s?.name).filter((n): n is string => !!n);

    const stats = (persona.stats ?? {}) as Record<string, unknown>;
    const interactionsRaw = stats.interactions ?? stats.interaction_count ?? stats.total_interactions;
    const interactions = typeof interactionsRaw === 'number' ? interactionsRaw : undefined;

    return { topPatterns, domainRules, antiPatterns, specializations, interactions };
}
