/********************************************************************************
 * Soriku IDE — chat model: fold engine SSE events into a view turn (pure)
 *
 * SPDX-License-Identifier: MIT
 ********************************************************************************/

import { SorikuSseEvent } from 'soriku-engine-client-ext/lib/common/engine-types';

export interface ChatToolCall {
    callId?: string;
    tool: string;
    args?: unknown;
    status: 'requested' | 'running' | 'done';
    result?: unknown;
}

export interface PlanTaskView {
    id: string;
    role: string;
    goal: string;
    model?: string;
}

export interface PendingPlan {
    planId: string;
    tasks: PlanTaskView[];
    costEur?: number;
}

export interface AssistantTurn {
    role: 'assistant';
    id: string;
    /** Model that produced this answer — surfaced for transparency (from SSE meta). */
    model?: string;
    /** Who responded (agent name / role) from SSE meta. */
    respondedBy?: string;
    conversationId?: string;
    text: string;
    toolCalls: ChatToolCall[];
    /** Models that collaborated on this answer (multi-worker / ensemble), for transparency. */
    workers: string[];
    /** Plan generated by the engine (Plan mode), shown for approval. */
    pendingPlan?: PendingPlan;
    /** The engine has parked the plan and is waiting for execute/cancel. */
    awaitingApproval?: boolean;
    /** Widget flag: this turn's plan must be approved by the user (Plan mode). */
    planNeedsApproval?: boolean;
    /** Latest progress message from the engine (status / plan / worker events). */
    phase?: string;
    status: 'streaming' | 'done' | 'error';
    error?: string;
}

export interface UserMessage {
    role: 'user';
    id: string;
    text: string;
}

export type ChatMessage = UserMessage | AssistantTurn;

export function createAssistantTurn(id: string): AssistantTurn {
    return { role: 'assistant', id, text: '', toolCalls: [], workers: [], status: 'streaming' };
}

/** The model behind a worker event — never the opaque worker_id (kept out of the UI list). */
function workerModelOf(event: SorikuSseEvent): string | undefined {
    return asString(event.model) ?? asString(event.model_id);
}

function parsePlanTasks(raw: unknown): PlanTaskView[] {
    if (!Array.isArray(raw)) {
        return [];
    }
    return raw.map((t, i) => {
        const task = (t && typeof t === 'object' ? t : {}) as Record<string, unknown>;
        return {
            id: asString(task.id) ?? `t${i + 1}`,
            role: asString(task.role) ?? 'worker',
            goal: asString(task.goal) ?? '',
            model: asString(task.preferred_model) ?? undefined,
        };
    });
}

function asString(value: unknown): string | undefined {
    return typeof value === 'string' ? value : undefined;
}

function callIdOf(event: SorikuSseEvent): string | undefined {
    return asString(event.request_id) ?? asString(event.confirmation_id) ?? asString(event.call_id) ?? asString(event.id);
}

/** Index of the last tool call that has not completed yet (for matching results without an id). */
function lastUnfinished(calls: ChatToolCall[], tool?: string): number {
    for (let i = calls.length - 1; i >= 0; i--) {
        if (calls[i].status !== 'done' && (tool === undefined || calls[i].tool === tool)) {
            return i;
        }
    }
    return -1;
}

/**
 * Upsert a tool call: reuse the matching/last-unfinished entry so an engine event and its
 * delegated `tool_request` don't show as duplicates, then resolve it on `tool_result`.
 */
function upsertToolCall(calls: ChatToolCall[], event: SorikuSseEvent, status: ChatToolCall['status']): void {
    const callId = callIdOf(event);
    const tool = asString(event.tool) ?? 'tool';
    let idx = callId ? calls.findIndex(c => c.callId === callId) : -1;
    if (idx < 0) {
        idx = lastUnfinished(calls, tool);
    }
    if (idx >= 0) {
        calls[idx] = { ...calls[idx], status, tool, args: event.args ?? calls[idx].args, callId: callId ?? calls[idx].callId };
    } else {
        calls.push({ callId, tool, args: event.args, status });
    }
}

/**
 * Fold one SSE event into the current assistant turn. Pure & immutable: returns a new turn so the
 * widget can keep prior snapshots and the logic is unit-testable without Theia or the network.
 */
export function reduceSseEvent(turn: AssistantTurn, event: SorikuSseEvent): AssistantTurn {
    const next: AssistantTurn = { ...turn, toolCalls: turn.toolCalls.slice(), workers: turn.workers.slice() };
    switch (event.type) {
        case 'meta':
            next.model = asString(event.model) ?? next.model;
            next.respondedBy = asString(event.responded_by) ?? asString(event.agent_name) ?? asString(event.role) ?? next.respondedBy;
            next.conversationId = asString(event.conversation_id) ?? next.conversationId;
            break;
        case 'model_switch':
        case 'model_assist':
            next.model = asString(event.to) ?? asString(event.model) ?? next.model;
            break;
        case 'routing':
            next.model = asString(event.model) ?? next.model;
            break;
        case 'status':
            next.phase = asString(event.content) ?? asString(event.message) ?? asString(event.status) ?? next.phase;
            break;
        case 'plan_generated': {
            next.phase = 'Planning…';
            const tasks = parsePlanTasks(event.tasks);
            const planId = asString(event.plan_id);
            if (planId) {
                next.pendingPlan = { planId, tasks, costEur: next.pendingPlan?.costEur };
            }
            break;
        }
        case 'deprecated_mode_translation':
            next.phase = 'Planning workers…';
            break;
        case 'plan_cost_estimated':
            if (next.pendingPlan && typeof event.estimated_cost_eur === 'number') {
                next.pendingPlan = { ...next.pendingPlan, costEur: event.estimated_cost_eur };
            }
            break;
        case 'plan_awaiting_execution':
            next.awaitingApproval = true;
            next.phase = 'Awaiting your approval';
            break;
        case 'worker_start': {
            next.awaitingApproval = false;
            const model = workerModelOf(event);
            if (model && !next.workers.includes(model)) {
                next.workers.push(model);
            }
            next.phase = model ? `Worker answering: ${model}` : 'Workers answering…';
            break;
        }
        case 'worker_done': {
            const model = workerModelOf(event);
            if (model && !next.workers.includes(model)) {
                next.workers.push(model);
            }
            break;
        }
        case 'synthesis_start':
            next.awaitingApproval = false;
            next.phase = 'Merging answers…';
            next.text = '';
            break;
        case 'synthesis_chunk':
            next.text += asString(event.chunk) ?? asString(event.content) ?? '';
            break;
        case 'synthesis_done': {
            const finalText = asString(event.final_text);
            if (finalText) {
                next.text = finalText;
            }
            next.model = asString(event.synthesizer_model) ?? next.model;
            next.phase = undefined;
            break;
        }
        case 'plan_done': {
            next.awaitingApproval = false;
            const finalText = asString(event.final_response);
            if (finalText) {
                next.text = finalText;
            }
            if (next.status === 'streaming') {
                next.status = 'done';
            }
            break;
        }
        case 'plan_cancelled':
            next.awaitingApproval = false;
            next.phase = undefined;
            if (next.status === 'streaming') {
                next.status = 'done';
            }
            if (!next.text) {
                next.text = 'Plan cancelled.';
            }
            break;
        case 'plan_failed':
        case 'plan_no_conductor':
            next.awaitingApproval = false;
            next.status = 'error';
            next.error = asString(event.error) ?? asString(event.reason) ?? 'Plan failed';
            break;
        case 'chunk':
            next.text += asString(event.content) ?? '';
            break;
        case 'answer': {
            const answer = asString(event.content) ?? asString(event.answer);
            if (answer) {
                next.text = answer;
            }
            break;
        }
        case 'confirm_tool':
            upsertToolCall(next.toolCalls, event, 'requested');
            break;
        case 'tool_request':
        case 'tool_call':
            upsertToolCall(next.toolCalls, event, 'running');
            break;
        case 'tool_result': {
            const callId = callIdOf(event);
            let idx = callId ? next.toolCalls.findIndex(t => t.callId === callId) : -1;
            if (idx < 0) {
                idx = lastUnfinished(next.toolCalls, asString(event.tool));
            }
            if (idx >= 0) {
                next.toolCalls[idx] = { ...next.toolCalls[idx], status: 'done', result: event.result ?? event.output };
            }
            break;
        }
        case 'error':
            next.status = 'error';
            next.error = asString(event.content) ?? asString(event.message) ?? 'Stream error';
            break;
        case 'done':
            if (next.status === 'streaming') {
                next.status = 'done';
            }
            break;
        default:
            break;
    }
    return next;
}

/** Human-readable label for the busy indicator while a turn is still streaming. */
export function busyPhase(turn: AssistantTurn): string {
    const running = turn.toolCalls.find(c => c.status !== 'done');
    if (running) {
        return running.status === 'requested' ? `Awaiting approval: ${running.tool}` : `Running ${running.tool}…`;
    }
    if (turn.phase) {
        return turn.phase;
    }
    return turn.text ? 'Writing…' : 'Thinking…';
}
